version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paper-grader-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/paper-grader
      - JWT_SECRET=your-secret-key-change-in-production
      - GEMINI_API_KEY=your-gemini-api-key
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: paper-grader-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongodb_data:
